import { ClothingItem } from '../types';

export const CLOTHING_CATEGORIES = [
  'All',
  'Tops',
  'Bottoms',
  'Dresses',
  'Outerwear',
  'Shoes',
  'Accessories',
] as const;

export const STATUS_FILTERS = ['All', 'Clean', 'Needs Washing', 'Favorites'] as const;

export const COLOR_OPTIONS = [
  'Blue',
  'Black',
  'White',
  'Gray',
  'Navy',
  'Red',
  'Green',
  'Brown',
  'Beige',
  'Khaki',
  'Pink',
  'Purple',
];

export const STYLE_OPTIONS = ['Casual', 'Formal', 'Business', 'Streetwear', 'Athletic', 'Bohemian'];

export const SEASON_OPTIONS = ['Spring', 'Summer', 'Fall', 'Winter', 'All'];

export const OCCASION_OPTIONS = ['Casual', 'Work', 'Formal', 'Sport', 'Date', 'Party', 'Travel', 'Lounge'];

export const initialClothingItems: ClothingItem[] = [
  {
    id: '1',
    name: 'Striped Button-Down',
    category: 'Tops',
    color: 'Blue',
    brand: 'Ralph Lauren',
    material: 'Cotton',
    style: 'Casual',
    seasons: ['Spring', 'Summer', 'Fall'],
    occasions: ['Work', 'Casual', 'Date'],
    image: 'https://picsum.photos/seed/striped-button-down/800/900',
    status: 'needs-washing',
    favorite: false,
    timesWorn: 18,
    lastWorn: 'Never',
    costPerWear: 4.72,
    wearCountSinceWash: 3,
    washThreshold: 5,
    avgWearsPerMonth: 18.0,
    sinceLast: '—',
    wearHistory: [
      { date: 'Jul 8, 2026' },
      { date: 'Jul 2, 2026' },
      { date: 'Jun 28, 2026' },
      { date: 'Jun 21, 2026' },
      { date: 'Jun 13, 2026' },
      { date: 'Jun 5, 2026' },
      { date: 'May 28, 2026' },
      { date: 'May 24, 2026' },
    ],
    addedDate: 'Jul 2, 2026',
  },
  {
    id: '2',
    name: 'Black Sneakers',
    category: 'Shoes',
    color: 'Black',
    brand: 'Nike',
    material: 'Mesh & Rubber',
    style: 'Athletic',
    seasons: ['All'],
    occasions: ['Sport', 'Casual'],
    image: 'https://picsum.photos/seed/black-red-sneakers/800/900',
    status: 'needs-washing',
    favorite: true,
    timesWorn: 24,
    lastWorn: '3 days ago',
    costPerWear: 3.2,
    wearCountSinceWash: 4,
    washThreshold: 6,
    avgWearsPerMonth: 12.0,
    sinceLast: '3 days',
    wearHistory: [{ date: 'Jul 5, 2026' }, { date: 'Jun 29, 2026' }, { date: 'Jun 20, 2026' }],
    addedDate: 'Jun 15, 2026',
  },
  {
    id: '3',
    name: 'Silver Watch',
    category: 'Accessories',
    color: 'Gray',
    brand: 'Fossil',
    material: 'Leather & Metal',
    style: 'Formal',
    seasons: ['All'],
    occasions: ['Work', 'Formal', 'Date'],
    image: 'https://picsum.photos/seed/silver-wrist-watch/800/900',
    status: 'needs-washing',
    favorite: true,
    timesWorn: 32,
    lastWorn: '1 day ago',
    costPerWear: 3.75,
    wearCountSinceWash: 5,
    washThreshold: 8,
    avgWearsPerMonth: 16.0,
    sinceLast: '1 day',
    wearHistory: [{ date: 'Jul 7, 2026' }, { date: 'Jul 1, 2026' }],
    addedDate: 'Apr 20, 2026',
  },
  {
    id: '4',
    name: 'Gray Hoodie',
    category: 'Tops',
    color: 'Gray',
    brand: 'Champion',
    material: 'Fleece',
    style: 'Streetwear',
    seasons: ['Fall', 'Winter'],
    occasions: ['Casual', 'Lounge'],
    image: 'https://picsum.photos/seed/gray-hoodie-back/800/900',
    status: 'needs-washing',
    favorite: false,
    timesWorn: 15,
    lastWorn: '5 days ago',
    costPerWear: 3.0,
    wearCountSinceWash: 2,
    washThreshold: 5,
    avgWearsPerMonth: 9.0,
    sinceLast: '5 days',
    wearHistory: [{ date: 'Jul 3, 2026' }, { date: 'Jun 25, 2026' }],
    addedDate: 'May 10, 2026',
  },
  {
    id: '5',
    name: 'Navy Blue Suit',
    category: 'Outerwear',
    color: 'Navy',
    brand: 'Hugo Boss',
    material: 'Wool',
    style: 'Formal',
    seasons: ['Fall', 'Winter'],
    occasions: ['Work', 'Formal'],
    image: 'https://picsum.photos/seed/navy-blue-suit-jacket/800/900',
    status: 'needs-washing',
    favorite: false,
    timesWorn: 6,
    lastWorn: '2 weeks ago',
    costPerWear: 41.5,
    wearCountSinceWash: 2,
    washThreshold: 10,
    avgWearsPerMonth: 2.0,
    sinceLast: '2 weeks',
    wearHistory: [{ date: 'Jun 22, 2026' }],
    addedDate: 'Jan 8, 2026',
  },
  {
    id: '6',
    name: 'Khaki Chinos',
    category: 'Bottoms',
    color: 'Khaki',
    brand: 'Dockers',
    material: 'Cotton',
    style: 'Casual',
    seasons: ['Spring', 'Summer', 'Fall'],
    occasions: ['Casual', 'Work'],
    image: 'https://picsum.photos/seed/khaki-chino-pants/800/900',
    status: 'needs-washing',
    favorite: false,
    timesWorn: 21,
    lastWorn: '4 days ago',
    costPerWear: 2.86,
    wearCountSinceWash: 3,
    washThreshold: 5,
    avgWearsPerMonth: 14.0,
    sinceLast: '4 days',
    wearHistory: [{ date: 'Jul 4, 2026' }, { date: 'Jun 27, 2026' }],
    addedDate: 'Mar 2, 2026',
  },
  {
    id: '7',
    name: 'Floral Summer Dress',
    category: 'Dresses',
    color: 'Pink',
    brand: 'Zara',
    material: 'Cotton Blend',
    style: 'Bohemian',
    seasons: ['Spring', 'Summer'],
    occasions: ['Casual', 'Date', 'Travel'],
    image: 'https://picsum.photos/seed/floral-summer-dress/800/900',
    status: 'clean',
    favorite: true,
    timesWorn: 9,
    lastWorn: '6 days ago',
    costPerWear: 6.4,
    wearCountSinceWash: 1,
    washThreshold: 4,
    avgWearsPerMonth: 5.0,
    sinceLast: '6 days',
    wearHistory: [{ date: 'Jul 2, 2026' }],
    addedDate: 'May 30, 2026',
  },
  {
    id: '8',
    name: 'Red Wool Scarf',
    category: 'Accessories',
    color: 'Red',
    brand: 'Uniqlo',
    material: 'Wool',
    style: 'Casual',
    seasons: ['Fall', 'Winter'],
    occasions: ['Casual', 'Travel'],
    image: 'https://picsum.photos/seed/red-wool-scarf/800/900',
    status: 'clean',
    favorite: false,
    timesWorn: 4,
    lastWorn: '3 weeks ago',
    costPerWear: 6.25,
    wearCountSinceWash: 0,
    washThreshold: 6,
    avgWearsPerMonth: 2.0,
    sinceLast: '3 weeks',
    wearHistory: [{ date: 'Jun 15, 2026' }],
    addedDate: 'Nov 2, 2025',
  },
];