import type { ClothingItem } from '../types/wardrobe'
import { estimateSeasons } from '../utils/seasonEstimator'

export const SAMPLE_ITEMS: ClothingItem[] = [
  { id: '1', name: 'White T-Shirt',  category: 'Top',         color: 'White', colorHex: '#f0f0f0', fabric: 'Cotton',    style: 'Casual',     occasion: 'Everyday', size: 'M',  createdAt: '2026-01-01', brand: 'Uniqlo', timesWorn: 8, lastWorn: null, dateAdded: '2026-06-30', cost: null, laundryStatus: 'Clean', seasons: estimateSeasons({ category: 'Top', fabric: 'Cotton', color: 'White' }), favorited: false },
  { id: '2', name: 'Blue Jeans',     category: 'Bottom',      color: 'Navy',  colorHex: '#1b2a4a', fabric: 'Denim',     style: 'Casual',     occasion: 'Everyday', size: 'M',  createdAt: '2026-01-02', brand: 'Levi\'s', timesWorn: 5, lastWorn: '2026-06-28', dateAdded: '2026-01-02', cost: 60, laundryStatus: 'Clean', seasons: estimateSeasons({ category: 'Bottom', fabric: 'Denim', color: 'Navy' }), favorited: false },
  { id: '3', name: 'White Sneakers', category: 'Shoes',       color: 'White', colorHex: '#f0f0f0', fabric: 'Leather',   style: 'Casual',     occasion: 'Everyday', size: 'M',  createdAt: '2026-01-03', brand: 'Adidas', timesWorn: 12, lastWorn: '2026-06-29', dateAdded: '2026-01-03', cost: 90, laundryStatus: 'Clean', seasons: estimateSeasons({ category: 'Shoes', fabric: 'Leather', color: 'White' }), favorited: true },
  { id: '4', name: 'Oxford Shirt',   category: 'Top',         color: 'Blue',  colorHex: '#3b82f6', fabric: 'Cotton',    style: 'Formal',     occasion: 'Work',     size: 'M',  createdAt: '2026-01-04', brand: '', timesWorn: 3, lastWorn: '2026-06-20', dateAdded: '2026-01-04', cost: null, laundryStatus: 'Needs Washing', seasons: estimateSeasons({ category: 'Top', fabric: 'Cotton', color: 'Blue' }), favorited: false },
  { id: '5', name: 'Chinos',         category: 'Bottom',      color: 'Khaki', colorHex: '#c3b091', fabric: 'Cotton',    style: 'Classic',    occasion: 'Work',     size: 'M',  createdAt: '2026-01-05', brand: '', timesWorn: 4, lastWorn: '2026-06-25', dateAdded: '2026-01-05', cost: null, laundryStatus: 'Clean', seasons: estimateSeasons({ category: 'Bottom', fabric: 'Cotton', color: 'Khaki' }), favorited: false },
  { id: '6', name: 'Bomber Jacket',  category: 'Outerwear',   color: 'Olive', colorHex: '#65753a', fabric: 'Nylon',     style: 'Streetwear', occasion: 'Everyday', size: 'L',  createdAt: '2026-01-06', brand: '', timesWorn: 1, lastWorn: null, dateAdded: '2026-01-06', cost: null, laundryStatus: 'Clean', seasons: estimateSeasons({ category: 'Outerwear', fabric: 'Nylon', color: 'Olive' }), favorited: false },
  { id: '7', name: 'Canvas Tote',    category: 'Accessories', color: 'Beige', colorHex: '#e8d5b7', fabric: 'Cotton',    style: 'Casual',     occasion: 'Everyday', size: 'XL', createdAt: '2026-01-07', brand: '', timesWorn: 6, lastWorn: '2026-06-15', dateAdded: '2026-01-07', cost: null, laundryStatus: 'In Laundry', seasons: estimateSeasons({ category: 'Accessories', fabric: 'Cotton', color: 'Beige' }), favorited: false },
  { id: '8', name: 'Track Pants',    category: 'Bottom',      color: 'Gray',  colorHex: '#888888', fabric: 'Polyester', style: 'Sporty',     occasion: 'Gym',      size: 'M',  createdAt: '2026-01-08', brand: '', timesWorn: 2, lastWorn: '2026-06-10', dateAdded: '2026-01-08', cost: null, laundryStatus: 'Clean', seasons: estimateSeasons({ category: 'Bottom', fabric: 'Polyester', color: 'Gray' }), favorited: false },
]
